Repository MTVS-3rd-TODORIAN/TODORIAN_BE, pull requests merged in 2024-08, with the labels that each got.

#2 [Setting] Templates
  .github/ISSUE_TEMPLATE/✅기능-이슈.md
  .github/ISSUE_TEMPLATE/🚨버그-리포트.md
  .github/pull_request_template.md
Labels: ⚙️ Setting

#3 Dev
  .github/ISSUE_TEMPLATE/✅기능-이슈.md
  .github/ISSUE_TEMPLATE/🚨버그-리포트.md
  .github/pull_request_template.md
Labels: ⚙️ Setting

#5 [Setting] Exception
  src/main/java/com/todorian/_core/error/GlobalExceptionHandler.java
  src/main/java/com/todorian/_core/error/exception/Exception400.java
  src/main/java/com/todorian/_core/error/exception/Exception401.java
  src/main/java/com/todorian/_core/error/exception/Exception403.java
  src/main/java/com/todorian/_core/error/exception/Exception404.java
  src/main/java/com/todorian/_core/error/exception/Exception500.java
  src/main/java/com/todorian/_core/utils/ApiUtils.java
Labels: ⚙️ Setting

#7 [Setting] Entity
  src/main/java/com/todorian/BaseTimeEntity.java
  src/main/java/com/todorian/member/domain/Member.java
Labels: ✨ Feature, ⚙️ Setting

#8 [Merge] dev
  src/main/java/com/todorian/BaseTimeEntity.java
  src/main/java/com/todorian/_core/error/GlobalExceptionHandler.java
  src/main/java/com/todorian/_core/error/exception/Exception400.java
  src/main/java/com/todorian/_core/error/exception/Exception401.java
  src/main/java/com/todorian/_core/error/exception/Exception403.java
  src/main/java/com/todorian/_core/error/exception/Exception404.java
  src/main/java/com/todorian/_core/error/exception/Exception500.java
  src/main/java/com/todorian/_core/utils/ApiUtils.java
  src/main/java/com/todorian/member/domain/Member.java
Labels: ✨ Feature, ⚙️ Setting

#14 Refactor: .gitignore
  .gitignore
Labels: 🔨 Refactor

#15 Test/feature/todo
  src/main/java/com/todorian/todo/domain/Todo.java
  src/main/java/com/todorian/todo/domain/TodoCreateRequestDTO.java
  src/main/java/com/todorian/todo/repository/TodoRepository.java
  src/main/java/com/todorian/todo/service/TodoService.java
Labels: ✨ Feature

#18 Test/feature/todo
  src/main/java/com/todorian/todo/domain/Todo.java
  src/main/java/com/todorian/todo/domain/TodoCreateRequestDTO.java
  src/main/java/com/todorian/todo/repository/TodoRepository.java
  src/main/java/com/todorian/todo/service/TodoService.java
  src/test/java/com/todorian/todo/service/TodoServiceTest.java
Labels: ✨ Feature, ✅ Test

#27 [Feat] createMember
  src/main/java/com/todorian/member/dto/MemberCreateRequestDTO.java
  src/main/java/com/todorian/member/repository/MemberRepository.java
  src/main/java/com/todorian/member/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/com/todorian/advertisement/AdvertisementTests.java
  src/test/java/com/todorian/member/MemberTests.java
Labels: ✨ Feature, ✅ Test

#28 [Feat] deleteMember
  src/main/java/com/todorian/member/service/MemberService.java
  src/test/java/com/todorian/member/MemberTests.java
Labels: ✨ Feature, ⚙️ Setting

#31 [Feat] Member
  .gitignore
  src/main/java/com/todorian/_core/config/QueryDSLConfig.java
  src/main/java/com/todorian/_core/config/SecurityConfig.java
  src/main/java/com/todorian/_core/jwt/JWTTokenFilter.java
  src/main/java/com/todorian/_core/jwt/JWTTokenProvider.java
  src/main/java/com/todorian/_core/utils/CustomUserDetail.java
  src/main/java/com/todorian/_core/utils/SecurityUtils.java
  src/main/java/com/todorian/member/controller/MemberAuthController.java
  src/main/java/com/todorian/member/controller/MemberOAuthController.java
  src/main/java/com/todorian/member/domain/Authority.java
  src/main/java/com/todorian/member/domain/Member.java
  src/main/java/com/todorian/member/domain/SocialType.java
  src/main/java/com/todorian/member/dto/MemberCreateRequestDTO.java
  src/main/java/com/todorian/member/dto/MemberRequestDTO.java
  src/main/java/com/todorian/member/dto/MemberResponseDTO.java
  src/main/java/com/todorian/member/property/KakaoProperties.java
  src/main/java/com/todorian/member/repository/MemberRepository.java
  src/main/java/com/todorian/member/repository/MemberRepositoryCustom.java
  src/main/java/com/todorian/member/repository/MemberRepositoryImpl.java
  src/main/java/com/todorian/member/service/MemberAuthService.java
  src/main/java/com/todorian/member/service/MemberOAuthService.java
  src/main/java/com/todorian/member/service/MemberService.java
  src/main/java/com/todorian/redis/domain/RefreshToken.java
  src/main/java/com/todorian/redis/repository/RefreshTokenRedisRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/todorian/member/MemberTests.java
Labels: ✨ Feature, 🔨 Refactor, ⚙️ Setting, ✅ Test

#33 Setting/logging
  .gitignore
  src/main/resources/application.yml
  src/main/resources/config/application-local.yml
  src/main/resources/log/console-appender.xml
  src/main/resources/log/file-error-appender.xml
  src/main/resources/log/file-info-appender.xml
  src/main/resources/log/file-warn-appender.xml
  src/main/resources/logback-spring.xml
Labels: ✨ Feature, ⚙️ Setting

#41 Update README.md
  README.md
Labels: 📃 Docs
