Repository MTVS-3rd-TODORIAN/TODORIAN_BE, pull requests merged in 2024-11, with the labels that each got.

#92 [Setting] Create docker-image.yml
  .github/workflows/docker-image.yml
Labels: ⚙️ Setting

#93 [Feat] CI/CD 설정
  .github/workflows/docker-image.yml
  Dockerfile
  Dockerrun.aws.json
  src/main/java/com/todorian/TodorianApplication.java
  src/main/java/com/todorian/_core/config/SecurityConfig.java
  src/main/java/com/todorian/_core/jwt/JWTTokenProvider.java
  src/main/java/com/todorian/member/command/application/controller/MemberAdminController.java
  src/main/java/com/todorian/member/command/application/controller/MemberAuthController.java
  src/main/java/com/todorian/member/command/application/controller/MemberOAuthController.java
  src/main/java/com/todorian/member/command/application/controller/MemberStatusController.java
  src/main/java/com/todorian/member/command/application/dto/MemberAuthRequestDTO.java
  src/main/java/com/todorian/member/command/application/dto/MemberAuthResponseDTO.java
  src/main/java/com/todorian/member/command/application/dto/MemberRequestDTO.java
  src/main/java/com/todorian/member/command/application/dto/MemberResponseDTO.java
  src/main/java/com/todorian/member/command/application/service/MemberAdminService.java
  src/main/java/com/todorian/member/command/application/service/MemberAuthService.java
  src/main/java/com/todorian/member/command/application/service/MemberStatusService.java
  src/main/java/com/todorian/member/command/domain/service/MemberOAuthService.java
  src/main/java/com/todorian/member/command/infrastructure/service/MemberOAuthServiceImpl.java
  src/main/java/com/todorian/system/command/application/controller/MemberSystemController.java
  src/main/java/com/todorian/system/command/domain/model/SystemSetting.java
  src/main/java/com/todorian/system/command/domain/model/property/SettingKey.java
  src/main/java/com/todorian/system/command/domain/model/property/ValueType.java
  src/main/resources/application.yml
  src/main/resources/config/application-local.yml
  src/main/resources/config/application-prod.yml
  src/main/resources/logback-spring.xml
  src/test/java/com/todorian/member/service/MemberAuthServiceTest.java
Labels: ⚙️ Setting

#91 Feat/todo/save
  src/main/java/com/todorian/point/application/dto/PointCreateRequestDTO.java
  src/main/java/com/todorian/point/domain/repository/PointRepository.java
  src/main/java/com/todorian/todo/application/controller/TodoController.java
  src/main/java/com/todorian/todo/application/dto/TodoRequestDTO.java
  src/main/java/com/todorian/todo/application/dto/TodoResponseDTO.java
  src/main/java/com/todorian/todo/application/service/BatchTaskScheduler.java
  src/main/java/com/todorian/todo/application/service/TodoService.java
  src/main/java/com/todorian/todo/domain/repository/TodoRepository.java
Labels: ✨ Feature, 🔨 Refactor

#97 Refactor: QueryDSL 삭제
  build.gradle
  src/main/java/com/todorian/_core/config/QueryDSLConfig.java
  src/main/java/com/todorian/member/command/domain/repository/MemberRepository.java
  src/main/java/com/todorian/member/command/domain/repository/MemberRepositoryCustom.java
  src/main/java/com/todorian/member/command/infrastructure/repository/MemberRepositoryImpl.java
Labels: 🔨 Refactor

#98 Reafactor: Dockerfile
  Dockerfile
Labels: 🔨 Refactor

#100 Refactor: application-prod.yml
  src/main/resources/config/application-prod.yml
Labels: 🔨 Refactor

#101 Refactor: .gitignore
  .gitignore
  Dockerfile
Labels: 🔨 Refactor

#112 refactor: 주간 목표 로직 수정, 할 일 로직 수정
  src/main/java/com/todorian/TodorianApplication.java
  src/main/java/com/todorian/todo/application/controller/TodoController.java
  src/main/java/com/todorian/todo/application/dto/TodoResponseDTO.java
  src/main/java/com/todorian/todo/application/service/TodoService.java
  src/main/java/com/todorian/weeklygoals/command/application/controller/WeeklyGoalsController.java
  src/main/java/com/todorian/weeklygoals/command/application/service/WeeklyGoalsService.java
  src/main/java/com/todorian/weeklygoals/command/domain/repository/WeeklyGoalsRepository.java
Labels: ✨ Feature, 🔨 Refactor

#116 Character, Member Character
  src/main/java/com/todorian/character/command/application/controller/CharacterController.java
  src/main/java/com/todorian/character/command/application/dto/CharacterFindResponseDTO.java
  src/main/java/com/todorian/character/command/application/dto/CharacterUpdateRequestDTO.java
  src/main/java/com/todorian/character/command/domain/model/Character.java
  src/main/java/com/todorian/membercharacter/command/application/controller/MemberCharacterController.java
  src/main/java/com/todorian/membercharacter/command/application/dto/MemberCharacterFindResponseDTO.java
  src/main/java/com/todorian/membercharacter/command/application/service/MemberCharacterFindService.java
  src/main/java/com/todorian/membercharacter/command/application/service/MemberCharacterUpdateService.java
  src/main/java/com/todorian/membercharacter/command/domain/model/MemberCharacter.java
  src/main/java/com/todorian/membercharacter/command/domain/repository/MemberCharacterRepository.java
  src/test/java/com/todorian/character/CharacterTests.java
  src/test/java/com/todorian/character/command/domain/service/CharacterTests.java
  src/test/java/com/todorian/memberCharacter/command/domain/service/MemberCharacterTests.java
Labels: ✨ Feature

#142 [Feat] Admin
  .gitignore
  src/main/java/com/todorian/admin/command/application/controller/AdminCommandController.java
  src/main/java/com/todorian/admin/command/application/dto/AdminCommandRequestDTO.java
  src/main/java/com/todorian/admin/command/application/dto/AdminCommandResponseDTO.java
  src/main/java/com/todorian/admin/command/application/service/AdminCommandService.java
  src/main/java/com/todorian/admin/query/controller/AdminQueryController.java
  src/main/java/com/todorian/admin/query/dto/AdminQueryResponseDTO.java
  src/main/java/com/todorian/admin/query/service/AdminQueryService.java
  src/main/java/com/todorian/character/command/application/service/CharacterService.java
  src/main/java/com/todorian/member/command/application/service/MemberAdminService.java
  src/main/java/com/todorian/member/command/domain/model/Member.java
  src/main/java/com/todorian/point/application/controller/PointController.java
  src/main/java/com/todorian/point/application/dto/PointCreateRequestDTO.java
  src/main/java/com/todorian/point/application/dto/PointRequestDTO.java
  src/main/java/com/todorian/point/application/service/PointService.java
  src/main/java/com/todorian/point/domain/model/Point.java
  src/main/java/com/todorian/point/domain/repository/PointRepository.java
  src/main/java/com/todorian/todo/application/controller/TodoController.java
  src/main/java/com/todorian/todo/application/service/BatchTaskScheduler.java
  src/main/java/com/todorian/todo/point/command/application/service/TodoPointCommandService.java
  src/main/java/com/todorian/todo/point/command/domain/model/TodoPoint.java
  src/main/java/com/todorian/todo/point/command/domain/model/TodoPointHistory.java
  src/main/java/com/todorian/todo/point/command/domain/model/TodoPointType.java
  src/main/java/com/todorian/todo/point/command/domain/model/UsageType.java
  src/main/java/com/todorian/todo/point/command/domain/repository/TodoPointCommandRepository.java
  src/main/java/com/todorian/todo/point/command/domain/repository/TodoPointHistoryCommandRepository.java
  src/main/resources/application.yml
  src/main/resources/config/application-local.yml
  src/main/resources/config/application-prod.yml
Labels: ✨ Feature, 🔨 Refactor, ⚙️ Setting

#143 feat: todo 성공 시 point 증가 로직 구현
  src/main/java/com/todorian/membercharacter/command/domain/model/MemberCharacter.java
  src/main/java/com/todorian/todo/application/controller/TodoController.java
  src/main/java/com/todorian/todo/point/command/application/service/TodoPointCommandService.java
Labels: ✨ Feature

#148 [Feat/admin] AOP 설정
  build.gradle
  src/main/java/com/todorian/TodorianApplication.java
  src/main/java/com/todorian/_core/aop/LoggingAspect.java
  src/main/java/com/todorian/_core/jwt/JWTTokenFilter.java
  src/main/java/com/todorian/_core/jwt/JWTTokenProvider.java
  src/main/java/com/todorian/_core/utils/ApiUtils.java
  src/main/java/com/todorian/member/command/application/service/MemberAuthService.java
  src/main/resources/logback-spring.xml
Labels: ✨ Feature, 🔨 Refactor, ⚙️ Setting

#152 [Feat] Point 정책 조회
  src/main/java/com/todorian/admin/query/controller/AdminQueryController.java
  src/main/java/com/todorian/admin/query/dto/AdminQueryResponseDTO.java
  src/main/java/com/todorian/admin/query/service/AdminQueryService.java
  src/main/java/com/todorian/system/command/application/controller/MemberSystemController.java
  src/main/resources/application.yml
Labels: ✨ Feature

#149 [Feat] Implement Friendship Management API
  src/main/java/com/todorian/friendship/command/application/controller/FriendshipController.java
  src/main/java/com/todorian/friendship/command/application/controller/FriendshipRecommendationController.java
  src/main/java/com/todorian/friendship/command/application/dto/FriendshipDTO.java
  src/main/java/com/todorian/friendship/command/application/dto/FriendshipQueryDTO.java
  src/main/java/com/todorian/friendship/command/application/service/FriendshipQueryService.java
  src/main/java/com/todorian/friendship/command/application/service/FriendshipRecommendationService.java
  src/main/java/com/todorian/friendship/command/application/service/FriendshipService.java
  src/main/java/com/todorian/friendship/command/domain/model/Friendship.java
  src/main/java/com/todorian/friendship/command/domain/model/FriendshipStatus.java
  src/main/java/com/todorian/friendship/command/domain/repository/FriendshipQueryRepository.java
  src/main/java/com/todorian/friendship/command/domain/repository/FriendshipRepository.java
Labels: ✨ Feature
