Repository MTVS-3rd-TODORIAN/TODORIAN_BE, pull requests merged in 2024-09, with the labels that each got.

#44 [Feat] [Test] Guestbook Entity, Service, Repository, CRUD Test Code
  src/main/java/com/todorian/guestbook/domain/model/GuestBook.java
  src/main/java/com/todorian/guestbook/domain/model/GuestBookCreateRequestDTO.java
  src/main/java/com/todorian/guestbook/domain/repository/GuestBookRepository.java
  src/main/java/com/todorian/guestbook/domain/service/GuestBookService.java
  src/test/java/com/todorian/guestbook/GuestBookServiceTest.java
Labels: ✨ Feature, ✅ Test

#54 [Feat] Friendship, FriendshipStatus entity
  src/main/java/com/todorian/friendship/command/domain/model/Friendship.java
  src/main/java/com/todorian/friendship/command/domain/model/FriendshipStatus.java
Labels: ✨ Feature

#57 [Feat] 회원 상태 관리
  README.md
  src/main/java/com/todorian/TodorianApplication.java
  src/main/java/com/todorian/_core/config/SecurityConfig.java
  src/main/java/com/todorian/_core/filter/CORSFilter.java
  src/main/java/com/todorian/member/command/application/controller/MemberAuthController.java
  src/main/java/com/todorian/member/command/application/controller/MemberStatusController.java
  src/main/java/com/todorian/member/command/application/dto/MemberRequestDTO.java
  src/main/java/com/todorian/member/command/application/service/MemberAuthService.java
  src/main/java/com/todorian/member/command/application/service/MemberStatusService.java
  src/main/java/com/todorian/member/command/domain/model/Member.java
  src/main/java/com/todorian/member/command/domain/model/Status.java
  src/main/java/com/todorian/todo/domain/Todo.java
  src/main/java/com/todorian/todo/domain/TodoCreateRequestDTO.java
  src/main/java/com/todorian/todo/repository/TodoRepository.java
  src/main/java/com/todorian/todo/service/TodoService.java
  src/test/java/com/todorian/member/service/MemberAuthServiceTest.java
  src/test/java/com/todorian/todo/service/TodoServiceTest.java
Labels: ✨ Feature, ⚙️ Setting

#60 [Feat] Front 연동 설정 추가
  src/main/java/com/todorian/TodorianApplication.java
  src/main/java/com/todorian/_core/filter/CORSFilter.java
  src/main/java/com/todorian/_core/jwt/JWTTokenProvider.java
  src/main/java/com/todorian/member/command/application/controller/MemberAuthController.java
  src/main/java/com/todorian/member/command/application/controller/MemberController.java
  src/main/java/com/todorian/member/command/application/controller/MemberOAuthController.java
  src/main/java/com/todorian/member/command/application/controller/MemberStatusController.java
  src/main/java/com/todorian/member/command/application/dto/MemberAuthRequestDTO.java
  src/main/java/com/todorian/member/command/application/dto/MemberAuthResponseDTO.java
  src/main/java/com/todorian/member/command/application/dto/MemberResponseDTO.java
  src/main/java/com/todorian/member/command/application/service/MemberAuthService.java
  src/main/java/com/todorian/member/command/application/service/MemberService.java
  src/main/java/com/todorian/member/command/application/service/MemberStatusService.java
  src/main/java/com/todorian/member/command/domain/model/Authority.java
  src/main/java/com/todorian/member/command/domain/model/Member.java
  src/main/java/com/todorian/member/command/domain/model/MemberStatus.java
  src/main/java/com/todorian/member/command/domain/model/property/Authority.java
  src/main/java/com/todorian/member/command/domain/model/property/SocialType.java
  src/main/java/com/todorian/member/command/domain/model/property/Status.java
  src/main/java/com/todorian/member/command/domain/service/MemberOAuthService.java
  src/main/java/com/todorian/member/command/infrastructure/service/MemberOAuthServiceImpl.java
  src/test/java/com/todorian/member/service/MemberAuthServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#74 [Refactor]
  .gitignore
  src/main/java/com/todorian/TodorianApplication.java
  src/main/java/com/todorian/_core/jwt/JWTTokenProvider.java
  src/main/resources/config/application-prod.yml
Labels: ✨ Feature
